```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(WVPlots)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(corrplot)
library(visreg)
library(ggseg)
library(ggsegSchaefer)
library(mgcv)
library(fastDummies)
library(lme4)
library(lmerTest)
library(car)
library(purrr)
k=3
```

```{r setup, include=FALSE}
process_gam <- function(data, formula_full, formula_null, n_rows, id, condition) {
  schaefer_H <- data.frame(age=1:n_rows, ID=id, Condition=condition)
  pvalue <- data.frame(age=1:n_rows, ID=id, Condition=condition)
  for (n in 1:n_rows) {
    col <- colnames(data)[n]
    gam.model <- gam(as.formula(paste(col, formula_full, sep = " ~ ")), data = data)
    gam.nullmodel <- gam(as.formula(paste(col, formula_null, sep = " ~ ")), data = data)
    anova_result <- anova(gam.nullmodel, gam.model, test='Chisq')
    pvalue$age[n] <- anova_result[2, "Pr(>Chi)"]
    sse.model <- sum((gam.model$y - gam.model$fitted.values)^2)
    sse.nullmodel <- sum((gam.nullmodel$y - gam.nullmodel$fitted.values)^2)
    partialRsq <- ifelse(sse.nullmodel != 0, (sse.nullmodel - sse.model) / sse.nullmodel, NA)
    if (coef(gam.model)[2]<0){
      schaefer_H$age[n] <-(-1) * partialRsq}
    else {
      schaefer_H$age[n] <-partialRsq}
  }
  print(pvalue$age)
  correctedpvalue <- data.frame(age=1:n_rows, ID=id, Condition=condition)
  correctedpvalue$age <- p.adjust(pvalue$age, method=c("fdr"))< 0.05
  pvalue$age <- pvalue$age < 0.05
  print(correctedpvalue$age)
  schaefer_H_extractp <- schaefer_H
  schaefer_H_extractp$age[!pvalue$age] <- NA
  schaefer_H_extractpadj <- schaefer_H
  schaefer_H_extractpadj$age[!correctedpvalue$age] <- NA
  return(list(schaefer_H,schaefer_H_extractp, schaefer_H_extractpadj))
}
```

```{r setup, include=FALSE}
extract_gam_stats <- function(model, data) {
  preds <- predict(model, newdata = data, type = "response")
  rss <- sum((data$age - preds)^2)
  tss <- sum((data$age - mean(data$age))^2)
  r_squared <- 1 - (rss / tss)
  p_value <- summary(model)$s.table[1, 4]  # This assumes you want the p-value of the first smooth term
  return(list(r_squared = r_squared, p_value = p_value))
}
```

```{r setup, include=FALSE}
process_lme <- function(data, formula_full, n_rows, id, condition) {
  schaefer_H <- data.frame(alcohol=1:n_rows)
  pvalue <- data.frame(alcohol=1:n_rows)
  ctrl <- lmeControl(opt = 'optim')
  for (n in 1:n_rows) {
    col <- colnames(data)[n]
    model <- lmer(as.formula(paste(col, formula_full, sep = " ~ ")), data = data, na.action = na.omit,control = lmerControl(optimizer = "optimx", optCtrl = list(method = "nlminb")))
    aov <- anova(model)
    pvalue$alcohol[n] <- aov$`Pr(>F)`[1]
    schaefer_H$alcohol[n] <- fixef(model)[2]
  }
  correctedpvalue <- data.frame(alcohol=1:n_rows)
  correctedpvalue$alcohol <- p.adjust(pvalue$alcohol, method=c("fdr"))< 0.05
  pvalue$alcohol <- pvalue$alcohol < 0.05
  schaefer_H_extractp <- schaefer_H
  schaefer_H_extractp$alcohol[!pvalue$alcohol] <- NA
  schaefer_H_extractpadj <- schaefer_H
  schaefer_H_extractpadj$alcohol[!correctedpvalue$alcohol] <- NA
  return(list(schaefer_H,schaefer_H_extractp,schaefer_H_extractpadj))
}
```

```{r setup, include=FALSE}
age_H <- read.csv(paste0('../derivatives/hurst.csv'))
age_H <- dummy_cols(age_H, select_columns = c("sub"))
#age_H <- age_H[age_H$run>1, ]
results <- process_lme(age_H, "run + age + sex + motion + (1 + run | sub)", 64, NA, NA)
write_csv(cbind(results[[1]], results[[2]], results[[3]]), '../derivatives/alcohol_effect.csv')
```

```{r setup, include=FALSE}
# limit motion
age_H <- read.csv(paste0('../derivatives/hurst.csv'))
age_H <- dummy_cols(age_H, select_columns = c("sub"))
age_H <- age_H[age_H$motion<0.012, ]
results <- process_lme(age_H, "run + age + sex + motion + (1 + run | sub)", 64, NA, NA)
write_csv(cbind(results[[1]], results[[2]], results[[3]]), '../derivatives/alcohol_motionlimited_effect.csv')
```